### ISSUE TITLE
Address the followup TODO's raised in the tmut PR

### ISSUE THREAD

**Issue by ascillitoe** [SeldonIO/alibi#771]
Address the follow-up TODO's raised in https://github.com/SeldonIO/alibi/pull/770.

**Comment by ascillitoe** [comment]
I think we can close this and ignore the remaining TODO's:

- [ ]  Fix the temperamental issue with the MacOS build, or just disable on MacOS for now. - _as @RobertSamoilescu pointed out, one can simply restart the desired build when the MacOS issue oocasionally causes the jobs to fail_.
- [ ] Move above instructions to CONTRIBUTING.md once finalised.
- [ ] Think about configuring the timeout option. To resume all the build workflows we'd need to ssh into each build separately and run touch continue, which isn't practical. This doesn't really matter if the default github action timeout is reasonable, but I'm not sure what it is. If it is too long we can set a shorter timeout specific to the tmut session. - _default GA timeout is 360 minutes. This seems reasonable considering we might want to spend a reasonable amount of time in a tmut session for debugging._
- [ ] Open equivalent PR for alibi-detect.
